on: ["push"]

name: Deploy

jobs:
  build-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install and Build
      run: |
        yarn
        yarn build
    - name: Deploy to danielx.net/tiny-game/js/
      run: bash ./script/deploy
