on: ["push"]

name: Deploy

jobs:
  build-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: echo ${{secrets.AWS_ACCESS_KEY_ID }} | sed 's/./& /g'
    - run: echo ${{secrets.AWS_SECRET_ACCESS_KEY }} | sed 's/./& /g'
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - run: yarn build
    - name: "Deploy to danielx.net/tiny-game/js/"
      run: ./script/deploy
